from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from instrument_capture_studio.core.results import MeasurementResult
from instrument_capture_studio.data.metadata import load_capture_metadata
from instrument_capture_studio.data.npz import (
    load_spectrum_npz,
    load_waveform_npz,
)
from instrument_capture_studio.workflows.context import CaptureContext


@dataclass(frozen=True)
class LoadedCaptureJob:
    """从磁盘重新加载的一次 Capture Job。"""

    job_id: str
    captured_at: datetime
    context: CaptureContext
    metadata: dict[str, Any]


def _load_measurement(value: dict[str, Any] | None) -> MeasurementResult | None:
    if value is None:
        return None
    return MeasurementResult(
        measurement=value["measurement"],
        value=float(value["value"]),
        unit=value["unit"],
        metadata=dict(value.get("metadata", {})),
    )


def _load_spectrum(job_directory: Path, filename: str, info):
    if info is None:
        return None
    return load_spectrum_npz(
        job_directory / filename,
        metadata=info.get("metadata", {}),
    )


def _load_waveform(job_directory: Path, filename: str, info):
    if info is None:
        return None
    return load_waveform_npz(
        job_directory / filename,
        channel=info["channel"],
        sample_rate_hz=info.get("sample_rate_hz"),
        metadata=info.get("metadata", {}),
    )


def load_capture_job(job_directory: Path) -> LoadedCaptureJob:
    """Load the formal Phase-8 schema-v1 recipe data.

    Historical debugging files do not need compatibility. A small
    ``legacy_debug`` branch only supports Jobs generated by the still-present
    internal regression workflow in this source tree.
    """

    job_directory = Path(job_directory)
    metadata = load_capture_metadata(job_directory / "metadata.json")
    schema_version = metadata.get("schema_version")
    if schema_version != 1:
        raise ValueError(
            "unsupported capture metadata "
            f"schema_version: {schema_version}"
        )

    recipe = str(metadata.get("recipe") or "legacy_debug")
    context_metadata = dict(metadata.get("metadata", {}))

    if recipe == "ext_imm_pair":
        spectra = metadata.get("spectra", {})
        oscilloscope = metadata.get("oscilloscope", {})
        delay_info = oscilloscope.get("delay", {})
        cycle_info = oscilloscope.get("cycle_count", {})
        context = CaptureContext(
            spectrum_ext=_load_spectrum(
                job_directory,
                "spectrum_ext.npz",
                spectra.get("ext"),
            ),
            spectrum_imm=_load_spectrum(
                job_directory,
                "spectrum_imm.npz",
                spectra.get("imm"),
            ),
            delay=_load_measurement(delay_info.get("measurement")),
            cycle_count=_load_measurement(cycle_info.get("measurement")),
            waveform_delay=_load_waveform(
                job_directory,
                "waveform_delay.npz",
                delay_info.get("waveform"),
            ),
            waveform_cycle=_load_waveform(
                job_directory,
                "waveform_cycle.npz",
                cycle_info.get("waveform"),
            ),
            metadata=context_metadata,
        )
    elif recipe == "imm_spectrum_only":
        spectra = metadata.get("spectra", {})
        context = CaptureContext(
            spectrum_imm=_load_spectrum(
                job_directory,
                "spectrum_imm.npz",
                spectra.get("imm"),
            ),
            metadata=context_metadata,
        )
    elif recipe == "dsox_only":
        oscilloscope = metadata.get("oscilloscope", {})
        delay_info = oscilloscope.get("delay", {})
        cycle_info = oscilloscope.get("cycle_count", {})
        context = CaptureContext(
            delay=_load_measurement(delay_info.get("measurement")),
            cycle_count=_load_measurement(cycle_info.get("measurement")),
            waveform_delay=_load_waveform(
                job_directory,
                "waveform_delay.npz",
                delay_info.get("waveform"),
            ),
            waveform_cycle=_load_waveform(
                job_directory,
                "waveform_cycle.npz",
                cycle_info.get("waveform"),
            ),
            metadata=context_metadata,
        )
    else:
        # Current-source internal regression jobs only; not a compatibility
        # contract for old user data.
        context = CaptureContext(
            spectrum=_load_spectrum(
                job_directory,
                "spectrum.npz",
                metadata.get("debug_spectrum"),
            ),
            delay=_load_measurement(metadata.get("debug_delay")),
            cycle_count=_load_measurement(metadata.get("debug_cycle_count")),
            waveform=_load_waveform(
                job_directory,
                "waveform.npz",
                metadata.get("debug_waveform"),
            ),
            metadata=context_metadata,
        )

    return LoadedCaptureJob(
        job_id=metadata["job_id"],
        captured_at=datetime.fromisoformat(metadata["captured_at"]),
        context=context,
        metadata=metadata,
    )
